# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install ROS Noetic
      - name: Install ROS Noetic
        run: |
          sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list'
          sudo apt install curl
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo apt update
          sudo apt install ros-noetic-ros-base
          sudo apt install python3-rosdep python3-rosinstall python3-rosinstall-generator python3-wstool build-essential
          sudo apt install python3-rosdep
          echo '=== FIRST STEP FINISHED ==='
      
      # Compile the source code
      - name: Compile src
        run: |
          source /opt/ros/noetic/setup.bash
          sudo rosdep init
          rosdep update
          mkdir -p ~/catkin_ws/src
          cd ~/catkin_ws && catkin_make
          ln -s $(pwd) ~/catkin_ws/src
          source ~/catkin_ws/devel/setup.bash
          sudo rosdep install -y --from-paths src --ignore-src --rosdistro noetic
          catkin_make
